export const PLAN_MODULES = [
  { key: 'availability_hours_enabled', label: 'Module 1 : Heures de disponibilité', description: "Permet de définir les horaires où l'agent répond automatiquement." },
  { key: 'payment_module_enabled', label: 'Module 2 : Paiement & Encaissement', description: "Intégration des passerelles de paiement pour vendre via l'IA." },
  { key: 'next_best_action_enabled', label: 'Module 3 : Assistant Proactif', description: "Relances automatiques intelligentes (paniers abandonnés, clients inactifs et commandes reportées)." },
  { key: 'conversion_score_enabled', label: 'Module 4 : Score de conversion', description: "Analyse la probabilité d'achat de chaque prospect." },
  { key: 'daily_briefing_enabled', label: 'Module 5 : Daily Briefing', description: "Résumé quotidien des activités envoyé sur WhatsApp." },
  { key: 'sentiment_routing_enabled', label: 'Module 6 : Sentiment routing', description: "Transfère à un humain si le client semble frustré." },
  { key: 'catalog_import_enabled', label: 'Module 7 : Import catalogue', description: "L'IA connaît vos produits via URL ou fichiers." },
  { key: 'human_handoff_alerts_enabled', label: 'Module 8 : Alertes Transfert Humain', description: "Notifications immédiates quand un agent demande de l'aide." },
  { key: 'analytics_module_enabled', label: 'Module 9 : Analytics & Statistiques', description: "Accès aux tableaux de bord et rapports détaillés sur les performances." },
  { key: 'flows_module_enabled', label: 'Module 10 : Flows (Flux de travail)', description: "Créez des scénarios d'automatisation visuels." },
  { key: 'whatsapp_status_enabled', label: 'Module 11 : Statut WhatsApp', description: "Publication de statuts WhatsApp via l'IA ou l'interface." },
  { key: 'leads_management_enabled', label: 'Module 12 : Gestion des Leads', description: "Gestion des prospects, analyse d'intention et conversion par l'IA." },
  { key: 'campaigns_module_enabled', label: 'Module 13 : Campagnes WhatsApp', description: "Envoi de messages en masse et planification récurrente." },
  { key: 'voice_responses_enabled', label: 'Module 14 : Réponses vocales (TTS)', description: "L'IA peut répondre par message vocal au lieu de texte." },
  { key: 'polls_module_enabled', label: 'Module 15 : Sondages', description: "Création et gestion de sondages WhatsApp." }
];

export const ACTION_LABELS = {
    login: 'Connexion', 
    register: 'Inscription', 
    login_failed: 'Échec connexion',
    create_user: 'Création compte', 
    update_user: 'Profil modifié', 
    soft_delete_user: 'Désactivé',
    hard_delete_user: 'Suppression définitive', 
    restore_user: 'Restauration',
    reset_password: 'Réinit. MDP', 
    add_credits: 'Crédits ajoutés', 
    create_agent: 'Agent créé',
    update_agent: 'Agent modifié', 
    delete_agent: 'Agent supprimé', 
    rollback_action: 'Rollback',
    update_plan: 'Plan mis à jour', 
    update_ai_model: 'Modèle IA modifié',
    add_knowledge: 'Connaissance ajoutée', 
    upload_knowledge: 'Fichier uploadé',
};
